"""Add missing contact fields

Revision ID: 3952a23de485
Revises: c199ad8a965e
Create Date: 2026-02-18 08:57:40.927257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3952a23de485'
down_revision: Union[str, None] = 'c199ad8a965e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('batch_number', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('batch_serial_number', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('date_received', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('ticket_number_nos', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('study_arm', sa.String(length=500), nullable=True))
    op.add_column('contacts', sa.Column('method', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'method')
    op.drop_column('contacts', 'study_arm')
    op.drop_column('contacts', 'ticket_number_nos')
    op.drop_column('contacts', 'date_received')
    op.drop_column('contacts', 'batch_serial_number')
    op.drop_column('contacts', 'batch_number')
    # ### end Alembic commands ###
