"""Create interview, interview_round, and response tables

Revision ID: c199ad8a965e
Revises: 6dd872a69153
Create Date: 2026-02-18 08:00:11.965716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c199ad8a965e'
down_revision: Union[str, None] = '6dd872a69153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('can_start_interview', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_rounds_contact_id'), 'interview_rounds', ['contact_id'], unique=False)
    op.create_index(op.f('ix_interview_rounds_id'), 'interview_rounds', ['id'], unique=False)
    op.create_index(op.f('ix_interview_rounds_round_number'), 'interview_rounds', ['round_number'], unique=False)
    op.create_index(op.f('ix_interview_rounds_scheduled_at'), 'interview_rounds', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_interview_rounds_status'), 'interview_rounds', ['status'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('current_question_index', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('decline_reason', sa.String(length=500), nullable=True),
    sa.Column('xform_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_contact_id'), 'interviews', ['contact_id'], unique=False)
    op.create_index(op.f('ix_interviews_created_at'), 'interviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)
    op.create_index(op.f('ix_interviews_round_number'), 'interviews', ['round_number'], unique=False)
    op.create_index(op.f('ix_interviews_status'), 'interviews', ['status'], unique=False)
    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responses_contact_id'), 'responses', ['contact_id'], unique=False)
    op.create_index(op.f('ix_responses_id'), 'responses', ['id'], unique=False)
    op.create_index(op.f('ix_responses_interview_id'), 'responses', ['interview_id'], unique=False)
    op.create_index(op.f('ix_responses_question_id'), 'responses', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_responses_question_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_interview_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_contact_id'), table_name='responses')
    op.drop_table('responses')
    op.drop_index(op.f('ix_interviews_status'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_round_number'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_created_at'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_contact_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_interview_rounds_status'), table_name='interview_rounds')
    op.drop_index(op.f('ix_interview_rounds_scheduled_at'), table_name='interview_rounds')
    op.drop_index(op.f('ix_interview_rounds_round_number'), table_name='interview_rounds')
    op.drop_index(op.f('ix_interview_rounds_id'), table_name='interview_rounds')
    op.drop_index(op.f('ix_interview_rounds_contact_id'), table_name='interview_rounds')
    op.drop_table('interview_rounds')
    # ### end Alembic commands ###
